services:
  grok-bot:
    build:
      context: . # Putanja do direktorijuma gde je vaš Dockerfile
      dockerfile: Dockerfile # Ime vašeg Dockerfile-a (npr. onog što počinje sa FROM python:3.12-slim)
    container_name: grok-bot-main
    env_file:
      - .env
    # Nema potrebe za command ako je CMD definisan u Dockerfile-u
    # command: uvicorn main:app --host 0.0.0.0 --port 8024 # Ostavite ako CMD nije u Dockerfile-u
    ports:
      - "8000:8000"
    volumes:
      - .:/app # Mapirate vaš kod u /app
      - ./html:/app/html # Ako main.py očekuje html u /app/html
      - ./logs:/app/logs # Ako main.py piše logove u /app/logs
    working_dir: /app
    restart: unless-stopped
    networks:
      - grok-network








  nginx:
    image: nginx:latest
    container_name: grok-bot-nginx
    ports:
      - "8080:80"
    volumes:
     # - nginx-cache:/var/cache/nginx
      - .:/app
      - ./html:/usr/share/nginx/html
      - ./logs:/logs
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    working_dir: /app
    depends_on:
      - grok-bot
    networks:
      - grok-network

networks:
  grok-network:
    driver: bridge

#volumes:
#  nginx-cache:
